
development:
  adapter: postgresql
  encoding: unicode
  database: TestE_development
  pool: 5
  username: colin
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: TestE_test
  pool: 5
  username: colin
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: TestE_production
  pool: 5
  username: colin
  password:
